### ISSUE TITLE
Error starting app without any site

### ISSUE THREAD

**Issue by leandrocp** [BeaconCMS/beacon#493] opened 2024-05-16 18:46 UTC
1. Create new Phx app
2. Install beacon dep
3. Run server

It should start the server and display the default Phx home page but instead it crashes with:

```
[error] Failure while translating Erlang's logger event
** (MatchError) no match of right hand side value: %{label: {:gen_statem, :terminate}, name: #PID<0.1138.0>, reason: {:error, %RuntimeError{message: "connect raised KeyError exception: key :database not found. The exception details are hidden, as they may contain sensitive data such as database credentials. You may set :show_sensitive_data_on_connection_error to true when starting your connection if you wish to see all of the details"}, [{Keyword, :fetch!, 2, [file: ~c"lib/keyword.ex", line: 602]}, {Postgrex.Protocol, :connect_endpoints, 6, [file: ~c"lib/postgrex/protocol.ex", line: 169]}, {DBConnection.Connection, :handle_event, 4, [file: ~c"lib/db_connection/connection.ex", line: 92]}, {:gen_statem, :loop_state_callback, 11, [file: ~c"gen_statem.erl", line: 1397]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}, log: [], state: Postgrex.Protocol, queue: [internal: {:connect, :init}], modules: [DBConnection.Connection], client_info: :undefined, callback_mode: :handle_event_function, postponed: [], timeouts: {0, []}, state_enter: false}
    (logger 1.17.0-dev) lib/logger/translator.ex:306: Logger.Translator.report_gen_statem_terminate/2
    (logger 1.17.0-dev) lib/logger/utils.ex:47: Logger.Utils.translate/5
    (logger 1.17.0-dev) lib/logger/utils.ex:25: Logger.Utils.translator/2
    (kernel 9.2) logger_backend.erl:101: :logger_backend.do_apply_filters/4
    (kernel 9.2) logger_backend.erl:86: :logger_backend.apply_filters/4
    (kernel 9.2) logger_backend.erl:32: :logger_backend.log_allowed/3
    (stdlib 5.2) gen_statem.erl:2591: :gen_statem.terminate/7
    (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by APB9785** [comment] 2024-08-16 20:24
can't reproduce anymore, likely resolved in a previous PR

**Closed by APB9785** 2024-08-16 20:24 UTC
Labels: bug, area:loader, roadmap
