### ISSUE TITLE
igniter install: extra_applications and applications in use

### ISSUE THREAD

**Issue by bcardarella** [BeaconCMS/beacon#669] opened 2024-11-25 19:02 UTC
Got this when generating a new project:

```
both :extra_applications and :applications was found in your mix.exs. You most likely want to remove the :applications key, as all applications are derived from your dependencies
```

**Comment by leandrocp** [comment] 2024-11-27 16:35
Hi @bcardarella that message is actually caused by https://hex.pm/packages/oembed. I'm closing this one in favor of https://github.com/BeaconCMS/beacon/issues/676

**Closed by leandrocp** 2024-11-27 16:35 UTC
